# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='daum_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
