# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20161128_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='frst_run_date',
            new_name='first_run_date',
        ),
    ]
