# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20161128_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='viewer_cnt',
        ),
    ]
