# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_remove_movie_viewer_cnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='naver_code',
        ),
    ]
