# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-01 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_fingouser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_email', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.FingoUser')),
            ],
        ),
    ]
