# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_userhash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingouser',
            name='user_img',
            field=models.ImageField(blank=True, upload_to='user_img'),
        ),
    ]
