# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20161205_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingouser',
            name='nickname',
            field=models.CharField(max_length=100),
        ),
    ]
