# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20161205_2243'),
        ('member', '0005_auto_20161206_1403'),
    ]

    operations = [
    ]
