# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-20 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_merge_20161206_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingouser',
            name='cover_img_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='fingouser',
            name='user_img_url',
            field=models.URLField(blank=True),
        ),
    ]
