# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-20 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20161220_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingouser',
            name='cover_img',
            field=models.ImageField(blank=True, upload_to='cover_img'),
        ),
    ]
