# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0006_remove_movie_viewer_cnt'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('score', models.FloatField(default=0.0)),
                ('watched_movie', models.BooleanField(default=False)),
                ('wish_movie', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.FingoUser')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='useractivity',
            unique_together=set([('user', 'movie')]),
        ),
    ]
