# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        ('fingo_statistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.FingoUser'),
        ),
        migrations.AlterUniqueTogether(
            name='useractivity',
            unique_together=set([('user', 'movie')]),
        ),
    ]
