# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingo_statistics', '0002_auto_20161130_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
