# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingo_statistics', '0003_auto_20161205_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='activity_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
