# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-08 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0006_merge_20161206_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserScores',
            fields=[
                ('user_statistics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user_statistics.UserStatistics')),
                ('point_five', models.IntegerField(default=0)),
                ('one', models.IntegerField(default=0)),
                ('one_point_five', models.IntegerField(default=0)),
                ('two', models.IntegerField(default=0)),
                ('two_point_five', models.IntegerField(default=0)),
                ('three', models.IntegerField(default=0)),
                ('three_point_five', models.IntegerField(default=0)),
                ('four', models.IntegerField(default=0)),
                ('four_point_five', models.IntegerField(default=0)),
                ('five', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='userstatistics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.FingoUser'),
        ),
    ]
