# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-08 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
        ('user_statistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Actor')),
            ],
        ),
        migrations.RemoveField(
            model_name='userstatistics',
            name='id',
        ),
        migrations.AlterField(
            model_name='userstatistics',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='member.FingoUser'),
        ),
        migrations.AddField(
            model_name='useractor',
            name='user_statistics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_statistics.UserStatistics'),
        ),
    ]
