# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-08 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
        ('user_statistics', '0002_auto_20161209_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDirector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Director')),
                ('user_statistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_statistics.UserStatistics')),
            ],
        ),
    ]
