# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-10 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20161209_1101'),
        ('user_statistics', '0003_userdirector'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(default=0.0)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Genre')),
                ('user_statistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_statistics.UserStatistics')),
            ],
        ),
        migrations.CreateModel(
            name='UserNation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(default=0.0)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Nation')),
                ('user_statistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_statistics.UserStatistics')),
            ],
        ),
    ]
