# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-11 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_statistics', '0004_usergenre_usernation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractor',
            name='count',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userdirector',
            name='count',
            field=models.FloatField(default=0.0),
        ),
    ]
